import os
import chromadb
import requests
from datetime import datetime
from chromadb.config import Settings
import os
from dotenv import load_dotenv
import html
from docx import Document
from docx.shared import Pt
import json
import os
import json
import requests
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


def publish_vulnerability_report_to_confluence(issues):
    """
    Publish structured vulnerability report to Confluence page.
    Replaces page content.
    """

    base_url = os.getenv("CONFLUENCE_BASE_URL")
    email = os.getenv("CONFLUENCE_EMAIL")
    api_token = os.getenv("CONFLUENCE_API_TOKEN")
    page_id = os.getenv("CONFLUENCE_PARENT_PAGE_ID")

    # ----------------------------
    # 1 Get Current Page Version
    # ----------------------------
    get_url = f"{base_url}/rest/api/content/{page_id}?expand=version"
    response = requests.get(get_url, auth=(email, api_token))

    if response.status_code != 200:
        raise Exception(f"Failed to fetch page: {response.text}")

    page_data = response.json()
    current_version = page_data["version"]["number"]

    # ----------------------------
    # 2️ Build HTML Body
    # ----------------------------
    body = f"""
    <h1>Vulnerability Report</h1>
    <p>Generated: {datetime.utcnow().isoformat()} UTC</p>
    """

    for issue in issues:
        meta = issue.get("metadata", {})
        code_snippet = issue.get("document", "")

        llm_raw = meta.get("llm_stored_result")
        root_cause = ""
        fixed_code = ""

        if llm_raw:
            try:
                llm_data = json.loads(llm_raw)
                root_cause = llm_data.get("root_cause", "")
                fixed_code = llm_data.get("fixed_code", "")
            except:
                pass

        body += f"""
        <hr/>
        <h2>Issue ID: {issue.get("id")}</h2>

        <p><strong>Rule:</strong> {meta.get("rule_id","")}</p>
        <p><strong>File:</strong> {meta.get("filepath","")}</p>
        <p><strong>Lines:</strong> {meta.get("start_line","")} - {meta.get("end_line","")}</p>
        <p><strong>Priority:</strong> {meta.get("priority_score","")}</p>
        <p><strong>Autofixable:</strong> {meta.get("is_autofixable","")}</p>
        <p><strong>Timestamp:</strong> {meta.get("timestamp","")}</p>
        """

        if root_cause:
            body += f"""
            <h3>Root Cause</h3>
            <p>{root_cause}</p>
            """

        if code_snippet:
            code_snippet = html.escape(code_snippet)
            body += f"""
            <h3>Original Code</h3>
            <pre>{code_snippet}</pre>
            """

        body += "<h3>Fixed Code</h3>"

        if fixed_code:
            fixed_code = html.escape(fixed_code)
            body += f"""
            <pre>{fixed_code}</pre>
            """
        else:
            body += """
            <p><em>Fixed code not yet generated by user.</em></p>
            """
    # ----------------------------
    # 3️Update Page
    # ----------------------------
    update_url = f"{base_url}/rest/api/content/{page_id}"

    payload = {
        "id": page_id,
        "type": "page",
        "title": page_data["title"],
        "version": {"number": current_version + 1},
        "body": {
            "storage": {
                "value": body,
                "representation": "storage"
            }
        }
    }

    update_response = requests.put(
        update_url,
        json=payload,
        auth=(email, api_token),
        headers={"Content-Type": "application/json"}
    )

    if update_response.status_code != 200:
        raise Exception(f"Update failed: {update_response.text}")

    print("Confluence page updated successfully.")

def create_vulnerability_word_report(issues, output_path="Vulnerability_Report.docx"):
    """
    Generate a simple Word vulnerability report.
    Each issue is rendered as its own section (no table).
    """

    doc = Document()
    doc.add_heading("Vulnerability Report", level=1)

    for issue in issues:
        meta = issue.get("metadata", {})
        code_snippet = issue.get("document", "")

        # Extract LLM stored result
        llm_raw = meta.get("llm_stored_result")
        root_cause = ""
        fixed_code = ""

        if llm_raw:
            try:
                llm_data = json.loads(llm_raw)
                root_cause = llm_data.get("root_cause", "")
                fixed_code = llm_data.get("fixed_code", "")
            except Exception:
                pass

        # ---------------------------
        # Issue Header
        # ---------------------------
        doc.add_heading(f"Issue ID: {issue.get('id')}", level=2)

        doc.add_paragraph(f"Rule: {meta.get('rule_id', '')}")
        doc.add_paragraph(f"File: {meta.get('filepath', '')}")
        doc.add_paragraph(f"Lines: {meta.get('start_line', '')} - {meta.get('end_line', '')}")
        doc.add_paragraph(f"Priority Score: {meta.get('priority_score', '')}")
        doc.add_paragraph(f"Autofixable: {meta.get('is_autofixable', '')}")
        doc.add_paragraph(f"Timestamp: {meta.get('timestamp', '')}")

        # ---------------------------
        # Root Cause
        # ---------------------------
        if root_cause:
            doc.add_heading("Root Cause", level=3)
            doc.add_paragraph(root_cause)

        # ---------------------------
        # Original Code
        # ---------------------------
        if code_snippet:
            doc.add_heading("Original Code", level=3)
            p = doc.add_paragraph()
            run = p.add_run(code_snippet)
            run.font.name = "Courier New"
            run.font.size = Pt(9)

        # ---------------------------
        # Fixed Code
        # ---------------------------
        if fixed_code:
            doc.add_heading("Fixed Code", level=3)
            p = doc.add_paragraph()
            run = p.add_run(fixed_code)
            run.font.name = "Courier New"
            run.font.size = Pt(9)

        doc.add_page_break()

    doc.save(output_path)
    print(f"Word report generated: {output_path}")

# Load .env file
load_dotenv()
# ----------------------------
# 1️ Export from Chroma
# ----------------------------


def fetch_issues_from_chroma():
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    persist_dir = os.path.join(BASE_DIR, "db", "chroma_db")

    client = chromadb.Client(
        Settings(
            persist_directory=persist_dir,
            is_persistent=True
        )
    )

    collection = client.get_collection("vuln_results")

    results = collection.get(include=["documents", "metadatas"])

    issues = []

    for i in range(len(results["ids"])):
        issues.append({
            "id": results["ids"][i],
            "document": results["documents"][i],
            "metadata": results["metadatas"][i] or {}
        })

    print("DEBUG SAMPLE ISSUE:")
    print(issues[0] if issues else "NO ISSUES FOUND")

    return issues


# ----------------------------
# 2️Convert to Confluence HTML
# ----------------------------

def generate_confluence_table(issues):
    rows = ""

    for issue in issues:
        meta = issue.get("metadata", {})
        import json
        code_snippet = issue.get("document", "")
        llm_raw = meta.get("llm_stored_result")
        fixed_code = ""
        root_cause = ""

        if llm_raw:
            try:
                root_cause = json.loads(llm_raw).get("root_cause", "")
            except:
                pass


        if llm_raw:
            try:
                llm_data = json.loads(llm_raw)
                fixed_code = llm_data.get("fixed_code", "")
            except:
                pass

        # Escape HTML to avoid breaking Confluence page
        code_snippet = html.escape(code_snippet)
        fixed_code = html.escape(fixed_code)

        rows += f"""
        <tr>
            <td>{issue.get("id","")}</td>
            <td>{meta.get("rule_id","")}</td>
            <td>{meta.get("filepath","")}</td>
            <td>{meta.get("start_line","")}</td>
            <td>{meta.get("end_line","")}</td>
            <td>{meta.get("priority_score","")}</td>
            <td>{meta.get("is_autofixable","")}</td>
            <td>{meta.get("timestamp","")}</td>
            <td>{root_cause}</td>
            <td>
                <pre>{code_snippet}</pre>
            </td>
            <td>
                <pre>{fixed_code}</pre>
            </td>
            
        </tr>
        """

    table = f"""
    <h1>Vulnerability Report</h1>
    <table style="width:100%; table-layout: fixed;">
        <tbody>
            <tr>
                <th>ID</th>
                <th>Rule</th>
                <th>File</th>
                <th>Start</th>
                <th>End</th>
                <th>Priority</th>
                <th>Autofixable</th>
                <th>Timestamp</th>
                <th>Root Cause</th>
                <th>Original and Fixed Code</th>
            </tr>
            {rows}
        </tbody>
    </table>
    """

    return table


# ----------------------------
# 3️Upload to Confluence
# ----------------------------

def upload_to_confluence(title, html_content):
    base_url = os.getenv("CONFLUENCE_BASE_URL")
    email = os.getenv("CONFLUENCE_EMAIL")
    api_token = os.getenv("CONFLUENCE_API_TOKEN")
    space_key = os.getenv("CONFLUENCE_SPACE_KEY")
    parent_page_id = os.getenv("CONFLUENCE_PARENT_PAGE_ID")

    url = f"{base_url}/rest/api/content"

    payload = {
        "type": "page",
        "title": title,
        "space": {"key": space_key},
        "ancestors": [{"id": parent_page_id}],
        "body": {
            "storage": {
                "value": html_content,
                "representation": "storage"
            }
        }
    }

    response = requests.post(
        url,
        json=payload,
        auth=(email, api_token),
        headers={"Content-Type": "application/json"}
    )

    if response.status_code not in [200, 201]:
        raise Exception(f"Failed: {response.status_code} {response.text}")

    print("Confluence page created successfully")
    return response.json()


# ----------------------------
# 4️⃣ Main Pipeline
# ----------------------------

def export_chroma_to_confluence():
    issues = fetch_issues_from_chroma()
    publish_vulnerability_report_to_confluence(issues)
    # title = f"Module Synk Report - {datetime.utcnow().date()}"
    # html = generate_confluence_table(issues)
    # upload_to_confluence(title, html)
    # issues = fetch_issues_from_chroma()
    # create_vulnerability_word_report(issues, "Vulnerability_Report.docx")


if __name__ == "__main__":
    issues = fetch_issues_from_chroma()
    create_vulnerability_word_report(issues, "Vulnerability_Report.docx")
    export_chroma_to_confluence()